
# 服务
server:
  port: 18008
spring:
  application:
    name: doraemon
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doraemon?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  profiles:
    active: prod

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.coget.doraemon.dataobject


# sys

# logging
logging:
  level:
    # 测试 debug 看详细日志
    cn.coget.doraemon.scheduler: debug
    # dao 开启 debug 模式 mybatis 输入 sql
    cn.coget.doraemon.dao: debug